[package]
name = "irisclassificationnn"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray= "0.17.1"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
rand = "0.9.2"
serde_json = "1.0"